name: AI Integrator Minimal

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate placeholder outputs
        run: |
          echo '{ "repo": "${{ github.repository }}", "generated_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)", "files": [] }' > AI_INDEX.json
          echo "# AI Notes" > AI_NOTES.md
          echo "- Repo: ${{ github.repository }}" >> AI_NOTES.md
          echo "- Generated: $(date -u)" >> AI_NOTES.md

      - name: Commit outputs
        run: |
          git config user.name "ai-integrator-bot"
          git config user.email "actions@github.com"
          git add AI_INDEX.json AI_NOTES.md || true
          git diff --staged --quiet || git commit -m "add AI_INDEX.json + AI_NOTES.md"
          git push
