name: File Lister

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List all files
        run: |
          echo "# Repo File List" > FILE_LIST.md
          find . -type f | sort >> FILE_LIST.md

      - name: Commit file list
        run: |
          git config user.name "ai-integrator-bot"
          git config user.email "actions@github.com"
          git add FILE_LIST.md
          if git diff --staged --quiet; then
            echo "No changes."
          else
            git commit -m "add FILE_LIST.md"
            git push
          fi
